CREATE TABLE [dbo].[GeneralData]
(
	[NumeFirma]                nvarchar(50)   NOT NULL,
	[NrOrdRegistruCom]         nvarchar(15)   NULL,
	[Localitate]               nvarchar(15)   NULL,
	[Telefon]                  nvarchar(15)   NULL,
	[Fax]                      nvarchar(15)   NULL,
	[Judet]                    nvarchar(15)   NULL,
	[Banca]                    nvarchar(50)   NULL,
	[Cont]                     nvarchar(34)   NULL,
	[CodFiscal]                nvarchar(12)   NULL,
	[CodFiscal2]               nvarchar(12)   NULL,
	[CodUnicInregistrare]      nvarchar(25)   NULL,
	[AdresaFirma]              nvarchar(50)   NULL,
	[LunaCurenta]              datetime       NULL,
	[PtrActMYSQL]              datetime       NULL,
	[PtrPrelContab]            datetime       NULL,
	[FunctieSemn1]             nvarchar(30)   NULL,
	[NumeSemn1]                nvarchar(50)   NULL,
	[FunctieSemn2]             nvarchar(30)   NULL,
	[NumeSemn2]                nvarchar(50)   NULL,
	[FunctieSemn3]             nvarchar(30)   NULL,
	[NumeSemn3]                nvarchar(50)   NULL,
	[FunctieSemn4]             nvarchar(30)   NULL,
	[NumeSemn4]                nvarchar(50)   NULL,
	[FunctieSemn5]             nvarchar(30)   NULL,
	[NumeSemn5]                nvarchar(50)   NULL,
	[Banca1]                   nvarchar(25)   NULL,
	[Filiala1]                 nvarchar(30)   NULL,
	[ContBancar1]              nvarchar(34)   NULL,
	[Banca2]                   nvarchar(25)   NULL,
	[Filiala2]                 nvarchar(30)   NULL,
	[ContBancar2]              nvarchar(34)   NULL,
	[Banca3]                   nvarchar(25)   NULL,
	[Filiala3]                 nvarchar(30)   NULL,
	[ContBancar3]              nvarchar(34)   NULL,
	[Banca4]                   nvarchar(25)   NULL,
	[Filiala4]                 nvarchar(30)   NULL,
	[ContBancar4]              nvarchar(34)   NULL,
	[Strada]                   nvarchar(50)   NULL,
	[Numar]                    nvarchar(15)   NULL,
	[Bloc]                     nvarchar(15)   NULL,
	[Scara]                    nvarchar(15)   NULL,
	[Etaj]                     nvarchar(15)   NULL,
	[Apartament]               nvarchar(15)   NULL,
	[Sector]                   nvarchar(15)   NULL,
	[Email]                    nvarchar(250)  NULL,
	[CAENactivitatePrincipala] char(4)        NULL,
	[CodPostal]                nvarchar(6)    NULL,
	[DataInfiintarii]          smalldatetime  NULL,
	[SediuCodJudet]            varchar(2)     NULL,
    [Logo]                     varbinary(MAX) NULL,
    [WebSite]                  nvarchar(128)  NULL,
    [NumeCunoscut]             nvarchar(200)  NULL,
	[CodTara]				   nvarchar(4)    NULL,
	CONSTRAINT [PK_dtDateGen] PRIMARY KEY CLUSTERED 
	(
		[NumeFirma] ASC
	)
)
GO