//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerWatchTower.Agent.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerWatchTower.Agent.View.Properties.UIRes", typeof(UIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string CapAlerts {
            get {
                return ResourceManager.GetString("CapAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string CapArchives {
            get {
                return ResourceManager.GetString("CapArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string CapReports {
            get {
                return ResourceManager.GetString("CapReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string ChkHasBackupDataGather {
            get {
                return ResourceManager.GetString("ChkHasBackupDataGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string ChkHasDriveDataGather {
            get {
                return ResourceManager.GetString("ChkHasDriveDataGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirroring.
        /// </summary>
        public static string ChkHasMirroringDataGather {
            get {
                return ResourceManager.GetString("ChkHasMirroringDataGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string ChkIsApproved {
            get {
                return ResourceManager.GetString("ChkIsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string ChkIsDeleted {
            get {
                return ResourceManager.GetString("ChkIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string HdrGuid {
            get {
                return ResourceManager.GetString("HdrGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string HdrPartnerName {
            get {
                return ResourceManager.GetString("HdrPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string HdrServerName {
            get {
                return ResourceManager.GetString("HdrServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string HdrWindowsVersion {
            get {
                return ResourceManager.GetString("HdrWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string LblArchives {
            get {
                return ResourceManager.GetString("LblArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string LblGuid {
            get {
                return ResourceManager.GetString("LblGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string LblPartnerName {
            get {
                return ResourceManager.GetString("LblPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string LblServerName {
            get {
                return ResourceManager.GetString("LblServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetric data.
        /// </summary>
        public static string LblTelemetricData {
            get {
                return ResourceManager.GetString("LblTelemetricData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string LblWindowsVersion {
            get {
                return ResourceManager.GetString("LblWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no alerts..
        /// </summary>
        public static string MsgEmptyAlertList {
            get {
                return ResourceManager.GetString("MsgEmptyAlertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Data.
        /// </summary>
        public static string TabGenericData {
            get {
                return ResourceManager.GetString("TabGenericData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string TitleServers {
            get {
                return ResourceManager.GetString("TitleServers", resourceCulture);
            }
        }
    }
}
